#####################
# 复写，主机名写在此处
#####################
# 12306
^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList url reject-200
#今日水印相机
^https?:\/\/p26-sign\.douyinpic\.com\/tos-cn-p-0015\/oIeN4tgDfAENcXYRCD9pCgBpZEANFAhokWDIX7~tplv-noop\.image url reject-200
#JD
# 京东
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start url reject-200
^https?:\/\/video-dsp\.pddpic\.com\/market-dsp-video\/ url reject
^https?:\/\/t-dsp\.pinduoduo\.com\/dspcb\/i\/mrk_ url reject
^https?:\/\/images\.pinduoduo\.com\/mrk\/ url reject
^https?:\/\/images\.pinduoduo\.com\/marketing_api\/ url reject
# DNS拦截
^https?:\/\/appconf\.mail\.163\.com\/mailmaster\/api\/http\/urlConfig\.do$ url reject-dict
^https?:\/\/cdn\.wup\.huya\.com\/monitor\/monitor\.jsp url reject
^https?:\/\/msglb\.91160\.com\/msg\/outer\/broker\/get$ url reject-dict
^https?:\/\/gslbali\.ximalaya\.com\/linkeye-cloud\/httpdns\/ url reject
^https?:\/\/ucdc\d?-upaas\.uc\.cn\/api\/v\d\/dns_query\? url reject-dict
^http?:\/\/((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(?:\/v?[0-9]+)?\/(?:sign_)?(?:(?:d|ss)[46]?|resolve)\?, url reject
^http?:\/\/W1031\.441.58\.64Vmd\?, url reject
^http?:\/\/cdn\.wup\.huya\.com\/launch\/queryHttpDns, url reject
^http?:\/\/xmc\.ximalaya\.com\/xmlymain-login-web\/login\/, url reject
^http?:\/\/W103|.37.155|.60Vfetch, url reject
^http?:\/\/((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?):\d+\/httpdns\/, url reject
hostname = ad.12306.cn, *.douyinpic.com, api.jd.com, video-dsp.pddpic.com, t-dsp.pinduoduo.com, images.pinduoduo.com, appconf.mail.163.com, msglb.91160.com, ucdc2-upaas.uc.cn

