# 12306
^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList url reject-200
#今日水印相机
^https?:\/\/p26-sign\.douyinpic\.com\/tos-cn-p-0015\/oIeN4tgDfAENcXYRCD9pCgBpZEANFAhokWDIX7~tplv-noop\.image url reject-200
#JD
# 京东
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start url reject-200
hostname = ad.12306.cn, *.douyinpic.com, api.jd.com
